# Generated by Django 3.2.6 on 2021-10-23 10:59

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(upload_to='panel/images/backgrounds/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='BodySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('slide_image', models.ImageField(upload_to='panel/images/backgrounds/', verbose_name='تصویر')),
                ('slider_text', models.TextField(blank=True, verbose_name='متن اسلایدر')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'اسلایدر بدنه صفحه اصلی',
                'verbose_name_plural': 'اسلایدر های بدنه صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('full_name', models.CharField(max_length=32, verbose_name='نام و نام خانوادگی')),
                ('image', models.ImageField(upload_to='panel/images/avatars/', verbose_name='آواتار')),
                ('position', models.CharField(max_length=32, verbose_name='جایگاه شغلی')),
            ],
            options={
                'verbose_name': 'بازخورد',
                'verbose_name_plural': 'بازخورد ها',
            },
        ),
        migrations.CreateModel(
            name='FooterSwiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'سوایپر پاورقی',
                'verbose_name_plural': 'سوایپر پاورقی',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('slide_image', models.ImageField(upload_to='panel/images/backgrounds/', verbose_name='ویدیو')),
                ('slider_text', models.TextField(blank=True, verbose_name='متن اسلایدر')),
                ('button_text', models.TextField(blank=True, verbose_name='متن دکمه')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'اسلایدر هدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدر های هدر صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='OtherWorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'دیگر طراحی حرفه ای',
                'verbose_name_plural': 'دیگر طراحی حرفه ای',
            },
        ),
        migrations.CreateModel(
            name='OurSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('counter', models.CharField(max_length=32, verbose_name='شمارنده')),
                ('feature', models.TextField(blank=True, verbose_name='ویژگی ها')),
            ],
            options={
                'verbose_name': 'آمار و ارقام',
                'verbose_name_plural': 'آمار و ارقام',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32, verbose_name='نام و نام خانوادگی')),
                ('image', models.ImageField(upload_to='panel/images/backgrounds/', verbose_name='تصویر')),
                ('position', models.CharField(max_length=32, verbose_name='مقعیت شقلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اعضای تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('old_price', models.IntegerField(verbose_name='قیمت قدیمی')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('feature', models.TextField(blank=True, verbose_name='ویژگی ها')),
                ('count', models.CharField(max_length=32, verbose_name='دوره پرداخت')),
                ('count_type', models.CharField(choices=[('M', 'Month'), ('Y', 'Years')], max_length=1, verbose_name='نوع دوره پرداخت')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'پلن فروش',
                'verbose_name_plural': 'پلن های فروش',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('under_title', models.CharField(max_length=32, verbose_name='زیر متن')),
                ('header_image', models.ImageField(upload_to='panel/images/backgrounds/', verbose_name='تصویر تیتر')),
                ('thumbnail', models.ImageField(upload_to='panel/images/backgrounds/', verbose_name='تصویر بندانگشتی')),
                ('header_text', models.CharField(max_length=200, verbose_name='متن تیتر')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوا')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'آنچه ما انجام می دهیم',
                'verbose_name_plural': 'آنچه ما انجام می دهیم',
            },
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('Strategy_title', models.TextField(verbose_name='عنوان استراتژی')),
                ('Strategy', models.TextField(verbose_name='ویژگی های استراتژی')),
                ('Development_title', models.TextField(verbose_name='عنوان دولوپمنت')),
                ('Development', models.TextField(verbose_name='ویژگی های دولوپمنت')),
            ],
            options={
                'verbose_name': 'ما کی هستیم',
                'verbose_name_plural': 'ما کی هستیم',
            },
        ),
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'طراحی حرفه ای',
                'verbose_name_plural': 'طراحی حرفه ای',
            },
        ),
    ]
