# Generated by Django 3.2.6 on 2021-10-09 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('feature', models.TextField(blank=True)),
                ('count', models.CharField(max_length=32)),
                ('count_type', models.CharField(choices=[('M', 'Month'), ('Y', 'Years')], max_length=1)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
