# Generated by Django 3.2.6 on 2021-10-10 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('slide_image', models.ImageField(upload_to='panel/images/backgrounds/')),
                ('slider_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
