# Generated by Django 3.2.6 on 2021-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_bodyslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyslider',
            name='slider_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='slider_text',
            field=models.TextField(blank=True),
        ),
    ]
