# Generated by Django 3.2.6 on 2021-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_footerswiper'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='panel/images/backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='FeesBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(blank=True)),
                ('full_name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='panel/images/backgrounds/')),
                ('position', models.CharField(max_length=32)),
            ],
        ),
    ]
