# Generated by Django 3.2.6 on 2021-10-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_about_feesback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeesBack',
            new_name='FeedBack',
        ),
    ]
