# Generated by Django 3.2.7 on 2021-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('slide_image', models.ImageField(upload_to='')),
                ('slider_text', models.CharField(max_length=200)),
                ('button_text', models.CharField(max_length=32)),
            ],
        ),
    ]
