# Generated by Django 3.2.6 on 2021-10-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='feature',
        ),
    ]
