# Generated by Django 3.2.6 on 2021-10-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_plans_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='feature',
            field=models.TextField(blank=True),
        ),
    ]
