# Generated by Django 3.2.7 on 2021-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_homeslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='slide_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
