# Generated by Django 3.2.7 on 2021-10-03 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
