# Generated by Django 3.2.7 on 2021-10-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_homeslider_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='slide_image',
            field=models.ImageField(upload_to='images/backgrounds/'),
        ),
    ]
